server:
  port: 9791
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.105:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.105:3306/db_project?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 1234
  redis:
    host: 192.168.150.105
    port: 6379

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*/*.xml

